"use client";

import { useState, useRef, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Sparkles, X, Sword, ArrowRight, Loader2, MessageSquare, Send } from "lucide-react";
import Button from "../ui/Button";
import Input from "../ui/Input";
import { useQuestStore } from "@/store/questStore";
import { QuestPriority } from "@/types/quest";

type Mode = "breakdown" | "chat";
type ChatMessage = { role: "user" | "assistant", content: string };

export default function AIAssistant() {
    const [isOpen, setIsOpen] = useState(false);
    const [mode, setMode] = useState<Mode>("breakdown");
    
    // Breakdown State
    const [prompt, setPrompt] = useState("");
    const [isGenerating, setIsGenerating] = useState(false);
    const [generatedQuests, setGeneratedQuests] = useState<any[]>([]);
    const { addQuest } = useQuestStore();

    // Chat State
    const [chatInput, setChatInput] = useState("");
    const [messages, setMessages] = useState<ChatMessage[]>([
        { role: "assistant", content: "Greetings Adventurer. Are you seeking a new quest, or do you need counsel?" }
    ]);
    const [isChatting, setIsChatting] = useState(false);
    const chatRef = useRef<HTMLDivElement>(null);

    // Auto scroll chat
    useEffect(() => {
        if (chatRef.current) {
            chatRef.current.scrollTop = chatRef.current.scrollHeight;
        }
    }, [messages]);

    const handleGenerate = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!prompt) return;

        setIsGenerating(true);
        setGeneratedQuests([]);

        try {
            const res = await fetch("/api/ai/breakdown", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ prompt }),
            });
            const data = await res.json();
            if (data.quests) {
                setGeneratedQuests(data.quests);
            }
        } catch (error) {
            console.error(error);
        } finally {
            setIsGenerating(false);
        }
    };

    const handleChat = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!chatInput.trim()) return;

        const newUserMsg: ChatMessage = { role: "user", content: chatInput };
        const newMessages = [...messages, newUserMsg];
        
        setMessages(newMessages);
        setChatInput("");
        setIsChatting(true);

        try {
            const apiMessages = newMessages.map(m => ({ role: m.role, content: m.content }));
            const res = await fetch("/api/ai/chat", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ messages: apiMessages }),
            });
            const data = await res.json();
            if (data.reply) {
                setMessages([...newMessages, { role: "assistant", content: data.reply }]);
            }
        } catch (error) {
            console.error(error);
            setMessages([...newMessages, { role: "assistant", content: "The connection to the ethereal plane was lost. Please try again." }]);
        } finally {
            setIsChatting(false);
        }
    };

    const handleAcceptAll = () => {
        generatedQuests.forEach((q) => {
            const newQuest: any = {
                id: `q-ai-${Math.random().toString(36).substring(2, 9)}`,
                workspaceId: "personal-1",
                title: q.title,
                description: "Generated by AI Master",
                difficulty: q.difficulty,
                priority: "medium" as QuestPriority,
                xp_reward: q.xp_reward,
                coin_reward: q.coin_reward,
                current_value: 0,
                target_value: 1,
                is_completed: false,
                type: "daily" as const,
                stat_rewards: {},
                tasks: [],
                created_at: new Date().toISOString()
            };
            addQuest(newQuest);
        });
        setMode("chat");
        setMessages([...messages, { role: "assistant", content: "Excellent! I have added those quests to your Mission Log. May the RNG gods be with you." }]);
        setPrompt("");
        setGeneratedQuests([]);
    };

    return (
        <>
            {/* FAB */}
            <motion.button
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
                onClick={() => setIsOpen(true)}
                className="fixed bottom-8 right-8 w-14 h-14 bg-gradient-to-r from-indigo-500 to-[var(--primary)] rounded-full flex items-center justify-center shadow-lg shadow-[var(--primary)]/30 z-40 border border-white/20"
            >
                <Sparkles className="text-white" size={24} />
            </motion.button>

            {/* Modal */}
            <AnimatePresence>
                {isOpen && (
                    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm">
                        <motion.div
                            initial={{ opacity: 0, y: 50, scale: 0.9 }}
                            animate={{ opacity: 1, y: 0, scale: 1 }}
                            exit={{ opacity: 0, y: 50, scale: 0.9 }}
                            className="bg-[#151921] w-full max-w-lg rounded-2xl border border-[var(--primary)]/30 shadow-2xl flex flex-col overflow-hidden max-h-[90vh]"
                        >
                            {/* Header */}
                            <div className="p-4 border-b border-white/10 flex items-center justify-between bg-white/5">
                                <div className="flex items-center gap-2">
                                    <Sparkles className="text-[var(--primary)]" size={20} />
                                    <h3 className="text-white font-bold">The Game Master</h3>
                                </div>
                                <div className="flex items-center gap-2">
                                    <div className="flex bg-black/30 rounded-lg p-1 border border-white/5">
                                        <button 
                                            onClick={() => setMode("breakdown")}
                                            className={`px-3 py-1.5 text-xs font-bold rounded-md transition-colors flex items-center gap-1.5 ${mode === 'breakdown' ? 'bg-indigo-500/20 text-indigo-400' : 'text-slate-400 hover:text-white'}`}
                                        >
                                            <Sword size={14} /> Quests
                                        </button>
                                        <button 
                                            onClick={() => setMode("chat")}
                                            className={`px-3 py-1.5 text-xs font-bold rounded-md transition-colors flex items-center gap-1.5 ${mode === 'chat' ? 'bg-emerald-500/20 text-emerald-400' : 'text-slate-400 hover:text-white'}`}
                                        >
                                            <MessageSquare size={14} /> Chat
                                        </button>
                                    </div>
                                    <button onClick={() => setIsOpen(false)} className="text-slate-400 hover:text-white p-1 rounded-md hover:bg-white/10 transition-colors ml-2">
                                        <X size={20} />
                                    </button>
                                </div>
                            </div>

                            {/* Body */}
                            <div className="overflow-hidden flex flex-col h-full bg-[#111318]">
                                {mode === "breakdown" ? (
                                    <div className="p-6 overflow-y-auto w-full">
                                        <p className="text-sm text-slate-400 mb-6 font-medium">
                                            Have a giant task? Tell me your goal, and I'll break it down into manageable quests with RPG rewards!
                                        </p>

                                        <form onSubmit={handleGenerate} className="space-y-4">
                                            <Input 
                                                placeholder="e.g. Build a new marketing landing page..." 
                                                value={prompt}
                                                onChange={(e) => setPrompt(e.target.value)}
                                                disabled={isGenerating}
                                            />
                                            <Button 
                                                type="submit" 
                                                className="w-full flex items-center justify-center gap-2 bg-indigo-600 hover:bg-indigo-500 border-none"
                                                disabled={!prompt || isGenerating}
                                            >
                                                {isGenerating ? <Loader2 className="animate-spin" size={18} /> : <Sparkles size={18} />}
                                                {isGenerating ? "Consulting scrolls..." : "Generate Magic Quests"}
                                            </Button>
                                        </form>

                                        <AnimatePresence>
                                            {generatedQuests.length > 0 && (
                                                <motion.div 
                                                    initial={{ opacity: 0, height: 0 }}
                                                    animate={{ opacity: 1, height: "auto" }}
                                                    className="mt-6 pt-6 border-t border-white/10"
                                                >
                                                    <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-3">Suggested Quests</h4>
                                                    <div className="space-y-2 mb-4">
                                                        {generatedQuests.map((q, idx) => (
                                                            <div key={idx} className="bg-black/40 rounded-lg p-3 border border-white/5">
                                                                <div className="text-sm text-white font-medium">{q.title}</div>
                                                                <div className="flex flex-wrap gap-2 mt-2">
                                                                    <span className="text-[10px] uppercase font-bold text-indigo-400 bg-indigo-400/10 px-1.5 py-0.5 rounded border border-indigo-400/20">{q.difficulty}</span>
                                                                    <span className="text-[10px] uppercase font-bold text-emerald-400 bg-emerald-400/10 px-1.5 py-0.5 rounded border border-emerald-400/20">+{q.xp_reward} XP</span>
                                                                    <span className="text-[10px] uppercase font-bold text-yellow-500 bg-yellow-500/10 px-1.5 py-0.5 rounded border border-yellow-500/20">+{q.coin_reward} Gold</span>
                                                                </div>
                                                            </div>
                                                        ))}
                                                    </div>
                                                    <Button variant="secondary" onClick={handleAcceptAll} className="w-full border-emerald-500/30 bg-emerald-500/10 text-emerald-400 hover:bg-emerald-500/20 transition-colors">
                                                        Accept All Quests <ArrowRight size={16} className="ml-2 inline" />
                                                    </Button>
                                                </motion.div>
                                            )}
                                        </AnimatePresence>
                                    </div>
                                ) : (
                                    <div className="flex flex-col h-[400px]">
                                        <div ref={chatRef} className="flex-grow p-4 overflow-y-auto space-y-4">
                                            {messages.map((msg, i) => (
                                                <div key={i} className={`flex ${msg.role === 'user' ? 'justify-end' : 'justify-start'}`}>
                                                    <div className={`max-w-[85%] p-3 rounded-2xl text-sm leading-relaxed ${
                                                        msg.role === 'user' 
                                                        ? 'bg-[var(--primary)] text-white' 
                                                        : 'bg-black/40 text-slate-200 border border-white/10'
                                                    }`}>
                                                        {msg.content}
                                                    </div>
                                                </div>
                                            ))}
                                            {isChatting && (
                                                <div className="flex justify-start">
                                                    <div className="max-w-[85%] p-3 rounded-2xl text-sm bg-black/40 text-slate-400 border border-white/10 flex items-center gap-2">
                                                        <Loader2 size={14} className="animate-spin" /> Game Master is typing...
                                                    </div>
                                                </div>
                                            )}
                                        </div>
                                        <div className="p-4 border-t border-white/5 bg-black/20">
                                            <form onSubmit={handleChat} className="flex items-center gap-2">
                                                <input 
                                                    type="text"
                                                    value={chatInput}
                                                    onChange={(e) => setChatInput(e.target.value)}
                                                    placeholder="Ask for motivation, reality check, or advice..."
                                                    className="flex-grow bg-[#151921] border border-white/10 text-white rounded-xl px-4 py-2.5 text-sm outline-none focus:border-[var(--primary)] transition-colors placeholder:text-slate-600"
                                                    disabled={isChatting}
                                                />
                                                <button 
                                                    type="submit" 
                                                    disabled={!chatInput.trim() || isChatting}
                                                    className="p-3 bg-[var(--primary)] text-white rounded-xl disabled:opacity-50 hover:bg-[var(--secondary)] transition-colors flex-shrink-0"
                                                >
                                                    <Send size={16} />
                                                </button>
                                            </form>
                                        </div>
                                    </div>
                                )}
                            </div>
                        </motion.div>
                    </div>
                )}
            </AnimatePresence>
        </>
    );
}
