"use client";

import { useState } from "react";
import { motion, AnimatePresence } from "framer-motion";
import { Sparkles, X, PlusCircle, ArrowRight, Loader2 } from "lucide-react";
import Button from "../ui/Button";
import Input from "../ui/Input";
import { useQuestStore } from "@/store/questStore";

export default function AIAssistant() {
    const [isOpen, setIsOpen] = useState(false);
    const [prompt, setPrompt] = useState("");
    const [isGenerating, setIsGenerating] = useState(false);
    const [generatedQuests, setGeneratedQuests] = useState<any[]>([]);
    const { addQuest } = useQuestStore();

    const handleGenerate = async (e: React.FormEvent) => {
        e.preventDefault();
        if (!prompt) return;

        setIsGenerating(true);
        setGeneratedQuests([]);

        try {
            const res = await fetch("/api/ai/breakdown", {
                method: "POST",
                headers: { "Content-Type": "application/json" },
                body: JSON.stringify({ prompt }),
            });
            const data = await res.json();
            if (data.quests) {
                setGeneratedQuests(data.quests);
            }
        } catch (error) {
            console.error(error);
        } finally {
            setIsGenerating(false);
        }
    };

    const handleAcceptAll = () => {
        generatedQuests.forEach((q) => {
            const newQuest = {
                id: `q-ai-${Math.random().toString(36).substring(2, 9)}`,
                workspaceId: "personal-1", // default workspace
                title: q.title,
                description: "Generated by AI Master",
                difficulty: q.difficulty,
                priority: "medium",
                xp_reward: q.xp_reward,
                coin_reward: q.coin_reward,
                current_value: 0,
                target_value: 1,
                is_completed: false,
                type: "daily" as const,
                stat_rewards: {},
                tasks: [],
                created_at: new Date().toISOString()
            };
            addQuest(newQuest);
        });
        setIsOpen(false);
        setPrompt("");
        setGeneratedQuests([]);
    };

    return (
        <>
            {/* FAB */}
            <motion.button
                whileHover={{ scale: 1.05 }}
                whileTap={{ scale: 0.95 }}
                onClick={() => setIsOpen(true)}
                className="fixed bottom-8 right-8 w-14 h-14 bg-gradient-to-r from-indigo-500 to-[var(--primary)] rounded-full flex items-center justify-center shadow-lg shadow-[var(--primary)]/30 z-40 border border-white/20"
            >
                <Sparkles className="text-white" size={24} />
            </motion.button>

            {/* Modal */}
            <AnimatePresence>
                {isOpen && (
                    <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/60 backdrop-blur-sm">
                        <motion.div
                            initial={{ opacity: 0, y: 50, scale: 0.9 }}
                            animate={{ opacity: 1, y: 0, scale: 1 }}
                            exit={{ opacity: 0, y: 50, scale: 0.9 }}
                            className="bg-[#151921] w-full max-w-lg rounded-2xl border border-[var(--primary)]/30 shadow-2xl flex flex-col overflow-hidden"
                        >
                            <div className="p-4 border-b border-white/10 flex items-center justify-between bg-white/5">
                                <div className="flex items-center gap-2">
                                    <Sparkles className="text-[var(--primary)]" size={20} />
                                    <h3 className="text-white font-bold">Ask the Game Master</h3>
                                </div>
                                <button onClick={() => setIsOpen(false)} className="text-slate-400 hover:text-white p-1 rounded-md hover:bg-white/10 transition-colors">
                                    <X size={20} />
                                </button>
                            </div>

                            <div className="p-6">
                                <p className="text-sm text-slate-400 mb-6">
                                    Have a giant task? Tell me what you want to achieve, and I'll break it down into manageable quests with rewards for you!
                                </p>

                                <form onSubmit={handleGenerate} className="space-y-4">
                                    <Input 
                                        placeholder="e.g. Build a new landing page for my product..." 
                                        value={prompt}
                                        onChange={(e) => setPrompt(e.target.value)}
                                        disabled={isGenerating}
                                        autoFocus
                                    />
                                    <Button 
                                        type="submit" 
                                        className="w-full flex items-center justify-center gap-2"
                                        disabled={!prompt || isGenerating}
                                    >
                                        {isGenerating ? <Loader2 className="animate-spin" size={18} /> : <Sparkles size={18} />}
                                        {isGenerating ? "Consulting the scrolls..." : "Generate Quests"}
                                    </Button>
                                </form>

                                {/* Results Area */}
                                <AnimatePresence>
                                    {generatedQuests.length > 0 && (
                                        <motion.div 
                                            initial={{ opacity: 0, height: 0 }}
                                            animate={{ opacity: 1, height: "auto" }}
                                            className="mt-6 pt-6 border-t border-white/10"
                                        >
                                            <h4 className="text-xs font-bold text-slate-400 uppercase tracking-wider mb-3">Suggested Quests</h4>
                                            <div className="space-y-2 mb-4 max-h-60 overflow-y-auto pr-2 scrollbar-thin">
                                                {generatedQuests.map((q, idx) => (
                                                    <div key={idx} className="bg-black/20 rounded-lg p-3 border border-white/5 flex items-start justify-between gap-4">
                                                        <div>
                                                            <div className="text-sm text-white font-medium">{q.title}</div>
                                                            <div className="flex flex-wrap gap-2 mt-2">
                                                                <span className="text-[10px] uppercase font-bold text-indigo-400 bg-indigo-400/10 px-1.5 py-0.5 rounded border border-indigo-400/20">{q.difficulty}</span>
                                                                <span className="text-[10px] uppercase font-bold text-emerald-400 bg-emerald-400/10 px-1.5 py-0.5 rounded border border-emerald-400/20">+{q.xp_reward} XP</span>
                                                                <span className="text-[10px] uppercase font-bold text-yellow-500 bg-yellow-500/10 px-1.5 py-0.5 rounded border border-yellow-500/20">+{q.coin_reward} Gold</span>
                                                            </div>
                                                        </div>
                                                    </div>
                                                ))}
                                            </div>
                                            <Button variant="secondary" onClick={handleAcceptAll} className="w-full border-indigo-500/30 hover:bg-indigo-500/10 hover:text-indigo-300 transition-colors">
                                                Accept All Quests <ArrowRight size={16} className="ml-2 inline" />
                                            </Button>
                                        </motion.div>
                                    )}
                                </AnimatePresence>
                            </div>
                        </motion.div>
                    </div>
                )}
            </AnimatePresence>
        </>
    );
}
